### ISSUE TITLE
Trigger webbook on successful payment

### ISSUE THREAD

**Issue by FazWamly** [Payfast/mod-gravityforms#10]
Hi There

We use a webhook on Gravity Forms but would only like this to be triggered on successful payment. Similar to how the delayed notifications work.

I reached out to Gravity Forms to ask if the webhook can support this on their end and this was their response:

"The Webhooks add-on does support the delayed payment feature but the payment add-on needs to support it as well in order to take advantage of it.

We do not however offer a PayFast add-on, you'd be using a third-party add-on to add support for that payment gateway to Gravity Forms. You'll need to contact the developer of the PayFast add-on and ask them if their add-on supports the GFPaymentAddOn::get_post_payment_actions_config() and GFPaymentAddOn::trigger_payment_delayed_feeds() methods which Gravity Forms added support for in version 2.4.13."

Is this something that can be implemented fairly soon?

**Comment by katrein** [comment]
Good day, Faz

Thank you for reaching out to us about this.

There are two custom hooks available in our plugin for Gravity Forms.

On a successful payment, we will call the hook named gform_payfast_payment_complete.
You can use this custom hook to run your custom requirements.

For a cancelled subscription, we will call the hook gform_payfast_payment_cancelled which you can set as you wish.

For both of these, the ITN data will be passed to the hook so you can access that data when deciding what your custom hook function will do.

If you have any further questions, feel free to reach out to us again.

**Comment by FazWamly** [comment]
Hi Katrein, thanks for the prompt response. 

I'm not 100% clued up on this, would this be something I set up using gravity forms webhook? Or would this require a different module?

I guess I'm asking, how do I actually implement this?

**Comment by katrein** [comment]
Hi Faz, it is my pleasure.

You can create a function for each of these hooks and add it to the functions.php found in your active themes folder.

For the successful payment, the custom hook will look like this and you add the code into this structure:

add_action( 'gform_payfast_payment_complete', function ( $pfData )  {
    // do stuff
} );

For more information and examples, please see the Gravity Forms documentation: 
https://docs.gravityforms.com/category/developers/hooks/

**Comment by FazWamly** [comment]
Okay yeah, I'm not gonna be able to do that(lack of skill). Was hoping there was a GUI option similar to how you have the notifications option in the Payfast Feed Section.

I just want to pop all the data from the form to a specific URL. I use Zoho creator for something else similar. Here is the code I use. Is there any chance you could expand on your example to include this below with the correct syntax. Im not a developer and not sure how to code the part that goes in "//Do stuff" :)  Even if I can't differentiate between the fields and it sends it all in one variable which I assume is the $pfData

```
myMap = Map:String();
	myMap.put("UniqueID",x.UniqueID);
	myMap.put("Package",x.Package_Selected);
	myMap.put("Total",x.Total);
	myMap.put("First Name",x.Name.first_name);
	myMap.put("Last Name",x.Name.last_name);
	myMap.put("Email",x.Email);
	myMap.put("Mobile",x.Phone_Number);
	myMap.put("OrgName",x.Organisation_Name);
	myMap.put("VATNumber",x.VAT_Number);
	myMap.put("ReferralCode",x.Referral_Code);
	myMap.put("Address1",x.Physical_Address.address_line_1);
	myMap.put("Address2",x.Physical_Address.address_line_2);
	myMap.put("Address3",x.Physical_Address.district_city);
	myMap.put("Address4",x.Physical_Address.state_province);
	myMap.put("Address5",x.Physical_Address.postal_Code);
	myMap.put("Address6",x.Physical_Address.country);
	resp = postUrl("https://webhookurlhere",myMap);

```
Any help would be greatly appreciated :)

**Comment by FazWamly** [comment]
1st prize would be an option like this but for webhooks 

![image](https://user-images.githubusercontent.com/72769157/95869508-bab4b980-0d6b-11eb-8bd4-d48cd57e8c4d.png)


I have a flimsy workaround now and would be happy to continue using the workaround for a period of time but only if this would be a feature you plan to add to the module in the near future.

**Comment by katrein** [comment]
Good day, Faz

Thank you for your interest in using PayFast.

Unfortunately, we do not provide development services and recommend reaching out to a professional developer to assist you with your custom development requirements.

**Comment by zunaidk** [comment]
Hi Katrein

Thanks -  I was able to use the gform_payfast_payment_complete hook.

Is there a hook for when the payment is unsuccessful ? 

Also does it work like other gravity form hooks where you can add the form id to the hook name so that it only runs for the specific form 

e.g. gform_payfast_payment_complete_10 if you only want it to run on form with id 10 ?

Finally-  I know that you don't provide custom development services but I would second a feature request to run a webhook only on successful payment. Webhooks are becoming much more prevalent and it would make it a lot easier if one could specify that a webhook should only run on either successful or non-successful payment (which can be specified)

Many thanks and kind regards
Zunaid
