### ISSUE TITLE
Notification emails after payment not sending

### ISSUE THREAD

**Issue by scross2020** [Payfast/mod-gravityforms#11]
Wordpress/Gravity Forms/Payfast add-on

Notification emails not sending when "Send notifications only when payment is received' is selected in the PayFast Feed settings. Any help here would be greatly appreciated.
BTW can only one email be processed this way? Is that the problem? I currently have 3 set - 2 with conditional logic, 1 for admin

**Comment by katrein** [comment]
Good day, thank you for reaching out to us about this.

The PayFast Feed option will trigger the Gravity Forms functions and logic once the payment has been made. It will trigger all the notifications. You may need to follow up with Gravity Forms on the outcome as PayFast simply activates this but won't be doing the processing of the conditions.

For further investigation, please provide more details of your query to our contact page and we will follow up with you on this: https://www.payfast.co.za/contact

**Comment by bruce-atkinson** [comment]
Hi @scross2020,

Just a quick update that notifications on event "Payment Complete" has now been added.
