### ISSUE TITLE
Unable to activate the plugin

### ISSUE THREAD

**Issue by blogbytes** [Payfast/mod-gravityforms#17]
Please assist with the below

Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /home/domain/public_html/wp-content/plugins/gravityformspayfast/payfast_common.inc on line 86

WordPress database error: [Table 'DB.wph9_rg_payfast' doesn't exist]
SELECT s.id, s.is_active, s.form_id, s.meta, f.title as form_title FROM wph9_rg_payfast s INNER JOIN wph9_gf_form f ON s.form_id = f.id

WordPress database error: [Table 'DB.wph9_gf_addon_payment_transaction' doesn't exist]
INSERT INTO wph9_gf_addon_payment_transaction (lead_id, transaction_type, transaction_id, is_recurring, amount, date_created) SELECT entry_id, transaction_type, transaction_id, is_renewal, amount, date_created FROM wph9_rg_payfast_transaction

Notice: An outdated add-on or custom code is attempting to access the wph9_rg_lead_meta table which is not valid in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data. Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2 in /home/domains/public_html/wp-content/plugins/gravityforms/gravityforms.php on line 6600
WordPress database error: [Table 'DB.wph9_rg_lead_meta' doesn't exist]
UPDATE wph9_rg_lead_meta SET meta_value='gravityformspayfast' WHERE meta_key='payment_gateway' AND meta_value='payfast'

Notice: An outdated add-on or custom code is attempting to access the wph9_rg_lead table which is not valid in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data. Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2 in /home/domains/public_html/wp-content/plugins/gravityforms/gravityforms.php on line 6600
WordPress database error: [Table 'DB.wph9_rg_lead' doesn't exist]
UPDATE wph9_rg_lead SET payment_status='Paid', payment_method='PayFast' WHERE payment_status='Approved' AND ID IN ( SELECT lead_id FROM wph9_rg_lead_meta WHERE meta_key='payment_gateway' AND meta_value='gravityformspayfast' )

**Comment by bruce-atkinson** [comment]
Hi @blogbytes, 

This may be a server-specific issue; the plugin requires PHP 8+.

Please kindly submit a ticket using https://support.payfast.help/portal/en/newticket, and the team will log this issue for you.
