### ISSUE TITLE
Email notifications not sending after payment

### ISSUE THREAD

**Issue by BryanIMS** [Payfast/mod-gravityforms#2]
Hi

Using this plugin with the latest version of gravity forms and the latest version of Wordpress.

I have selected notifications only to be sent once payment is made. I am currently testing in sandbox, the redirects work and the payment status has changed to paid from the entries but the notifications are not sending.

Could this be a bug?

**Comment by Brendon-P** [comment]
Hi

Thank you for contacting us, the change has been made to allow for delayed notifications.

Have a great day.
