### ISSUE TITLE
Callback issue

### ISSUE THREAD

**Issue by aasghar551** [Payfast/mod-gravityforms#21]
Hi
Payment status doesn't updating in the gravity forms. Payments showing pending on gravity form. It was working before but not working after we updated the plugin.

**Comment by bruce-atkinson** [comment]
Hi @aasghar551,

Please kindly [contact the Payfast support team](https://payfast.io/contact/) to log a support ticket for this matter.

**Comment by aasghar551** [comment]
Already sent them a message but they doesn't responded yet.

**Comment by bruce-atkinson** [comment]
@aasghar551 what is your ticket number?

**Comment by aasghar551** [comment]
They haven't provided the ticket number.

**Comment by aasghar551** [comment]
I have submitted another query and they are not providing the ticket number. Just showing this message after the submission
"Thanks for contacting us! We will get in touch with you shortly."
![2024-05-24_05-30-42](https://github.com/Payfast/mod-gravityforms/assets/23654213/75c4caac-767d-48a1-b2bf-db7063eff0b7)

**Comment by bruce-atkinson** [comment]
@aasghar551 further communication will happen on the ticket thread. CS has advised that this is awaiting a response from yourself.

Please kindly respond on the ticket.
