### ISSUE TITLE
PayGate GravityForms 1.5.4 not working

### ISSUE THREAD

**Issue by Daseeds786** [Payfast/mod-gravityforms#22]
Hi Dev team,

Trust you are well. Reported to PayFast Integration team a week ago. Unfortunately service is extremely terrible and unreliable without any solution till today. 

Im currently running Wordpress 6.5.3 with Gravity Forms 2.8.11. 

The Payment itself is working fine with Gravity Froms but I am having the following issues:

1) The PayFast email receipt - The Hi {Name} is displaying the PayFast account holders name and not pulling the name from the form.
2) If the payment goes through, the payment details is not being updated and is stuck on "Pending" on the entry page as a result we do not know which transactions are approved or declined.
3) Due to the payment being stuck on pending, the Payment Complete event notification does not get sent out even though the payment has gone through.

Can someone involved in the dev team of the plugin please assist? Because the PayFast team is clueless...

Thanks in advance.

**Comment by bruce-atkinson** [comment]
Hi @Daseeds786,

What is your ticket number?

**Comment by Daseeds786** [comment]
1169296

**Comment by Daseeds786** [comment]
Why is the ticket closed with nothing being resolved?

**Comment by bruce-atkinson** [comment]
@Daseeds786 further communication will happen on the ticket thread. CS has advised that this is awaiting a response from yourself.

Please kindly respond on the ticket.
