### ISSUE TITLE
Possibility of putting the plugin in the root of the repo

### ISSUE THREAD

**Issue by seagyn** [Payfast/mod-gravityforms#3]
Hi there,

I'm wanting to use composer to manage that addon but because it's got a default WP folder structure (which doesn't cater for sub directory installs or Bedrock setups such as I have).

What would be ideal, is if the repo itself is the plugin which will allow me to run this through packagist. If you'd like I could make a PR for this change?

**Comment by Brendon-P** [comment]
Hi seagyn

Please can you submit a ticket to support@payfast.co.za and one of our devs will get back to you.

Thank you
The PayFast Team
