### ISSUE TITLE
Once-off and recurring payment on one form

### ISSUE THREAD

**Issue by snapalot** [Payfast/mod-gravityforms#4]
Hi guys

It seems like it's not possible to let someone choose on the form if the payment must be once-off or recurring. Our donation form should be able to receive both once-off and recurring payments.

![gravityformspayfast-scr](https://user-images.githubusercontent.com/1741694/28769156-a99fdc00-75da-11e7-88a1-fa7e818fb478.png)

Thanks
Kobus

**Comment by seagyn** [comment]
Hi @snapalot 

You could create 2 payment feeds with a conditional statement in it. For example, you have a dropdown in the form saying once-off and reoccuring and then have two feeds that if it's once-off, do Products and Services etc.

**Comment by snapalot** [comment]
Great stuff, thank you @seagyn :)

**Comment by Brendon-P** [comment]
Thanks again @seagyn
