### ISSUE TITLE
Gravity Forms User Registration Integration - User is registered even if payment is cancelled

### ISSUE THREAD

**Issue by intramall** [Payfast/mod-gravityforms#8]
When used with the Gravity Forms user registration extension - the person completing the form is registered even if payment is cancelled. Need integration with User Registration to process the feed only when a payment is received. This option can be seen for example on the Gravity Forms Paypal payment option.

**Comment by isgak-salie** [comment]
Good Day @intramall,

Thank you for contacting us with your suggestion.

We have taken your integration suggestion into consideration and will do an investigation for the integration. Once our investigation has been completed will we have feedback on this.

Please follow up on support@payfast.co.za for feedback.
