### ISSUE TITLE
Add fields for Payfast to collect

### ISSUE THREAD

**Issue by sverleis** [Payfast/mod-gravityforms#9]
We are having more and more queries for our Gravity Forms to push a different unique ID to Payfast, so that the Finance teams can allocate a payment to a specific unique identifier (not the form entry's unique ID).
Is there any way to get this implemented?

**Comment by bruce-atkinson** [comment]
Good Day @sverleis l,

Thank you for contacting us with your suggestion.

Please kindly submit this request to [support@payfast.co.za](mailto:support@payfast.co.za).
